### ISSUE TITLE
Error in TFsharp. Only when building for android

### ISSUE THREAD

**Issue by Bricktheworld** [shaqian/TF-Unity-ARFoundation#1]
Assets\TensorFlow\Detector.cs(59,9): error CS0103: The name 'TensorFlowSharp' does not exist in the current context

Code: "#if UNITY_ANDROID
        TensorFlowSharp.Android.NativeBinding.Init ();
#endif"

Assets\TensorFlow\Classifier.cs(31,9): error CS0103: The name 'TensorFlowSharp' does not exist in the current context

Code: "#if UNITY_ANDROID
        TensorFlowSharp.Android.NativeBinding.Init ();
#endif"

I'm not certain if these lines are necessary or not

**Comment by Bricktheworld** [comment]
Sorry, all I had to do was enable editor in tensorflowsharp.android dll import

**Comment by syedali1621** [comment]
@Bricktheworld which unity version are you using ?
i still not able to build an apk?
